Transient Pool
nv-morpheus/SRF pull request #107
Opened 2022-06-30 07:26 UTC by ryanolson

```cpp
/**
 * @brief ReusablePool of memory::buffers that are used as reusable reference-counted monotonic memory resources
 *
 * TransientPool is a ReusablePool of memory::buffers from which smaller buffers are allocated similar to a monotonic
 * memory resource, i.e. pointer pusing stack; however the TransientBuffer or Transient<T> object pull from the pool
 * hold a SharedReusable<memory::buffer> which keeps the entire monotonic stack from returning to the resuable pool
 * until all objects created on a given stack are deallocated.
 *
 * Allocation of Transisent object should be incredibly fast; even faster than the Reusable/SharedResuable on which they
 * are based, since a single Reusable<memory::buffer> might back 10s-1000s of allocations dependending on size.
 *
 * It is critical that all Transient object allocated from a pool have similar life cycles
 */
```

2022-06-30 22:06 UTC, dagardner-nv requested changes
Looks good, but can you add a few more comments to the header?

2022-06-30 22:06 UTC, dagardner-nv commented on src/internal/memory/transient_pool.hpp
> +    std::size_t bytes() const;
Maybe just a comment of what bytes represents here, is it the size of `data` or is it the total size of `TransientBuffer`>

Also is `addr` null terminated?

2022-06-30 22:06 UTC, dagardner-nv commented on src/internal/memory/transient_pool.hpp
> + * memory resource, i.e. pointer pusing stack; however the TransientBuffer or Transient<T> object pull from the pool
```suggestion
 * memory resource, i.e. pointer pushing stack; however the TransientBuffer or Transient<T> object pull from the pool
```

2022-06-30 22:13 UTC, ryanolson commented on src/internal/memory/transient_pool.hpp
> +        CHECK_LT(sizeof(T), bytes());
the buffer should be allocated to be a bit larger than sizeof(T) to allow for proper alignment.

it should be

CHECK_LE(sizeof(T) + alignof(T), bytes());

2022-06-30 22:13 UTC, ryanolson commented on src/internal/memory/transient_pool.hpp
> +        CHECK_LT(sizeof(T), bytes());
```suggestion
        CHECK_LE(sizeof(T) + alignof(T), bytes());
```

2022-06-30 22:43 UTC, dagardner-nv approved these changes

2022-07-01 05:24 UTC, ryanolson commented
@dagardner-nv - i added explicit move constructors and assignment operators since the default ones do not play nice with raw pointers.

I also added the ability to pass arguments for the `await_object<T>(...)` call.

Let me know if you think of any thing I might have missed.

2022-07-02 03:26 UTC, closed without merging