Add codecov action
nv-morpheus/SRF pull request #197
Opened 2022-10-19 18:05 UTC by dagardner-nv

2022-10-21 16:24 UTC, mdemoret-nv requested changes
Couple of things.

2022-10-21 17:18 UTC, dagardner-nv commented on ci/scripts/github/common.sh
> +    popd
It's checking sha1, sha256 and sha512 
This is what was in their docs on how to verify it:
https://about.codecov.io/blog/validating-the-bash-script-on-ci/?utm_medium=article&utm_source=blog&utm_campaign=security-incident&utm_content=validating-bash-on-ci&utm_term=clicked-inline-cta

2022-10-21 17:43 UTC, dagardner-nv commented on codecov.yml
> +#Configuration File for CodeCov
I moved it to the `.github` dir

2022-10-24 16:33 UTC, mdemoret-nv approved these changes
LGTM

2022-10-24 16:34 UTC, mdemoret-nv commented
@gpucibot merge

2022-10-24 16:34 UTC, merged